### ISSUE TITLE
Add MIT license 

### ISSUE THREAD

**Issue by andreybleme** [andreybleme/protractor-sublime-snippets#2]
Add a MIT license on README and on the repository.
Such as: https://github.com/caiogondim/bullet-train-oh-my-zsh-theme/blob/master/LICENSE

**Comment by ilimugur** [comment]
on it.

**Comment by ilimugur** [comment]
Look OK? @andreybleme

**Comment by andreybleme** [comment]
Yes it does @ilimugur ! :100: 

Thanks!
